title = "Social Force Config File"

[scene]
enable_group = false
agent_radius = 0.35
# the maximum speed doesn't exceed 1.3x initial speed
max_speed_multiplier = 1.3
tau = 0.5
resolution = 50

[desired_force]
factor = 1.0
# The relaxation distance of the goal
goal_threshold = 0.2
# How long the relaxation process would take
relaxation_time = 0.5

[social_force]
factor = 5.1
# Moussaid-Helbing 2009
# relative importance of position vs velocity vector
lambda_importance = 2.0
# define speed interaction
gamma = 0.35
n = 2
# define angular interaction
n_prime = 3

[obstacle_force]
factor = 10.0
# the standard deviation of obstacle force
sigma = 0.2
# threshold to trigger this force
threshold = 3.0

[group_coherence_force]
factor = 3.0

[group_repulsive_force]
factor = 1.0
# threshold to trigger this force
threshold = 0.55

[group_gaze_force]
factor = 4.0
# fielf of view
fov_phi = 90.0

[types]
# 成人 (type=0)
[types.0.scene]
agent_radius = 0.35
step_width = 0.4
max_speed_multiplier = 1.3
tau = 0.5

[types.0.forces.goal_attractive_force]
factor = 1.0

[types.0.forces.ped_repulsive_force]
factor = 1.5
v0 = 2.1
sigma = 0.3
fov_phi = 130.0
fov_factor = 0.5

[types.0.forces.space_repulsive_force]
factor = 1.0
u0 = 10
r = 0.2

[types.0.forces.desired_force]
factor = 1.0
goal_threshold = 0.2
relaxation_time = 0.5

[types.0.forces.social_force]
factor = 3.0
lambda_importance = 2.0
gamma = 0.35
n = 2
n_prime = 3

[types.0.forces.obstacle_force]
factor = 3.0
sigma = 0.2
threshold = 5.0

# 老人 (type=1)
[types.1.scene]
agent_radius = 0.4
step_width = 0.3
max_speed_multiplier = 0.9
tau = 0.5

[types.1.forces.goal_attractive_force]
factor = 0.8

[types.1.forces.ped_repulsive_force]
factor = 1.3
v0 = 1.5
sigma = 0.35
fov_phi = 100.0
fov_factor = 0.3

[types.1.forces.space_repulsive_force]
factor = 1.2
u0 = 8
r = 0.25

[types.1.forces.desired_force]
factor = 1.0
goal_threshold = 0.5
relaxation_time = 0.2

[types.1.forces.social_force]
factor = 2.0
lambda_importance = 1.8
gamma = 0.4
n = 2
n_prime = 3

[types.1.forces.obstacle_force]
factor = 3.0
sigma = 0.2
threshold = 3.0

# 子供 (type=2)
[types.2.scene]
agent_radius = 0.3
step_width = 0.3
max_speed_multiplier = 1.1
tau = 0.4

[types.2.forces.goal_attractive_force]
factor = 1.2

[types.2.forces.ped_repulsive_force]
factor = 2.0
v0 = 2.5
sigma = 0.25
fov_phi = 80.0
fov_factor = 0.4

[types.2.forces.space_repulsive_force]
factor = 1.5
u0 = 12
r = 0.15

[types.2.forces.desired_force]
factor = 1.2
goal_threshold = 0.2
relaxation_time = 0.5

[types.2.forces.social_force]
factor = 4.0
lambda_importance = 1.8
gamma = 0.3
n = 3
n_prime = 4

[types.2.forces.obstacle_force]
factor = 2.0
sigma = 0.2
threshold = 4.0 